services:
  zytho:
    build:
      context: .
      dockerfile: prod.Dockerfile
    env_file: .env
    container_name: zytho
    ports:
      - "5173:5173"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.zytho.rule=Host(`zytho.mizkyosia.fr`)"
      - "traefik.http.routers.zytho.entrypoints=web"
      - "traefik.http.services.zytho.loadbalancer.server.port=5173"

networks:
  traefik-public:
    external: true
